// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7wH-sj8BnGvcbRE2pzbGBIBwCaTGwmw',
    appId: '1:956761330395:web:d04d1fc57c83474db5f2fe',
    messagingSenderId: '956761330395',
    projectId: 'chem4u-3b77f',
    authDomain: 'chem4u-3b77f.firebaseapp.com',
    storageBucket: 'chem4u-3b77f.appspot.com',
    measurementId: 'G-49C2QD99RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1TDVmnMV8nQr-LH-3wnkd_sgHzAdY8KY',
    appId: '1:956761330395:android:8749b17a72a7bbffb5f2fe',
    messagingSenderId: '956761330395',
    projectId: 'chem4u-3b77f',
    storageBucket: 'chem4u-3b77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVir2mR_jt0CLqvExV1YjqKhFzvwMZ5gE',
    appId: '1:956761330395:ios:f79e089829de3c2eb5f2fe',
    messagingSenderId: '956761330395',
    projectId: 'chem4u-3b77f',
    storageBucket: 'chem4u-3b77f.appspot.com',
    iosBundleId: 'com.example.adminLogin',
  );
}
